---
abstract: 'Dist::Zilla release plugin to upload via scp'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Upload-SCP
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dist::Zilla::Plugin::Upload::SCP:
    file: lib/Dist/Zilla/Plugin/Upload/SCP.pm
    version: 0.002
requires:
  Dist::Zilla::Role::Releaser: 0
  Moose: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Tiny: 0
  Net::OpenSSH: 0.60
  Path::Tiny: 0
  autodie: 2.00
  namespace::autoclean: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/dist-zilla-plugin-upload-scp/issues
  homepage: https://metacpan.org/release/Dist-Zilla-Plugin-Upload-SCP
  repository: git://github.com/dagolden/dist-zilla-plugin-upload-scp.git
version: 0.002
